version: "2"
services:
  tabby_wikidb:
    image: mongo
    command: "--smallfiles --bind_ip tabby_wikidb"
    environment:
      - "MONGO_LOG_DIR=/dev/null"
    volumes:
      - ./data/mongo:/data/db
    labels:
      - "traefik.enable=false"

  tabby_wikijs:
    image: "requarks/wiki:latest"
    depends_on:
      - tabby_wikidb
    environment:
      WIKI_ADMIN_EMAIL: ${WIKI_ADMIN_EMAIL}
      GIT_USER_NAME:    ${GIT_USER_NAME}
      GIT_USER_PASS:    ${GIT_USER_PASS}
      GIT_REPO_URL:     ${GIT_REPO_URL}
    volumes:
      - ./config.yml:/var/wiki/config.yml
      - /var/log/www/tabby:/logs
    labels:
      - "traefik.docker.network=thenetwork"
      - "traefik.enable=true"
      - "traefik.port=3000"
      - "traefik.backend=tabby_wikijs"
      - "traefik.frontend.rule=Host:tabby.scholarslab.org"

networks:
  default:
    external:
      name: thenetwork
